# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.box_version = "9.3.0"

  config.vm.box_check_update = false
	config.vm.network :private_network, ip: '192.168.56.180'
	config.vm.synced_folder "/Users/ram/Documents/web/sf34-rest-api/Projects", "/var/www",
      nfs: true,
      mount_options: ['actimeo=1']
	config.hostsupdater.aliases = ["local.offer.api", "local.offer.admin"]

  	config.vm.provider "virtualbox" do |v|
      		v.memory = 1024
      		v.cpus = 2
      		v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      		v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

	config.vm.provision :shell, :path => "php7-2"
end
